server:
  port: 8181

spring:
  application:
    name: ting-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启基于服务名发现
          enabled: true
          # 服务名小写
          lower-case-service-id: true

eureka:
  instance:
    # instance-id: ${spring.application.name}:${server.port}
    # 显示ip地址
    prefer-ip-address: true
  client:
    # 此客户端是否应从eureka服务器获取eureka注册表信息。
    fetch-registry: true
    # 指示此实例是否应向eureka服务器注册其信息以供其他人发现。
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
